use crate::domain::global_assets::GlobalAsset;

pub(crate) fn asset_fixtures() -> Vec<GlobalAsset> {
    vec![
        format_sample_asset(
            "bitcoin",
            "BTC",
            "Bitcoin",
            "crypto",
            "/assets/bitcoin",
            &["btc", "bitcoin", "bit coin"],
            10,
        ),
        format_sample_asset(
            "ethereum",
            "ETH",
            "Ethereum",
            "crypto",
            "/assets/ethereum",
            &["eth", "ether", "ethereum"],
            20,
        ),
        format_sample_asset(
            "usdc",
            "USDC",
            "USD Coin",
            "crypto",
            "/assets/usdc",
            &[
                "usdc",
                "usd coin",
                "usdc coin",
                "usdc coin usd",
                "circle usd coin",
                "circle usdc",
                "dollar coin",
            ],
            30,
        ),
        format_sample_asset(
            "wrapped-bitcoin",
            "WBTC",
            "Wrapped Bitcoin",
            "crypto",
            "/assets/wrapped-bitcoin",
            &["wbtc", "wrapped bitcoin", "wrapped btc"],
            35,
        ),
        format_sample_asset(
            "gold",
            "XAU",
            "Gold",
            "commodity",
            "/assets/gold",
            &[
                "gold",
                "oro",
                "oro de ley",
                "xau",
                "precious metal",
                "metal precioso",
            ],
            40,
        ),
        format_sample_asset(
            "mantle",
            "MNT",
            "Mantle",
            "crypto",
            "/assets/mantle",
            &["mnt", "mantle"],
            50,
        ),
        format_sample_asset(
            "near",
            "NEAR",
            "NEAR Protocol",
            "crypto",
            "/assets/near",
            &["near", "near protocol"],
            60,
        ),
        format_sample_asset(
            "aave",
            "AAVE",
            "Aave",
            "crypto",
            "/assets/aave",
            &["aave"],
            70,
        ),
        format_sample_asset(
            "ausd",
            "AUSD",
            "AUSD",
            "stablecoin",
            "/assets/ausd",
            &["ausd"],
            80,
        ),
        format_sample_asset(
            "usds",
            "USDS",
            "Sky Dollar",
            "stablecoin",
            "/assets/usds",
            &["usds", "sky dollar"],
            90,
        ),
        format_sample_asset(
            "fbtc",
            "FBTC",
            "FBTC",
            "crypto",
            "/assets/fbtc",
            &["fbtc"],
            100,
        ),
        format_sample_asset(
            "gho",
            "GHO",
            "GHO",
            "stablecoin",
            "/assets/gho",
            &["gho"],
            110,
        ),
        format_sample_asset(
            "mpdao",
            "MPDAO",
            "MPDAO",
            "crypto",
            "/assets/mpdao",
            &["mpdao"],
            120,
        ),
        format_sample_asset(
            "stnear",
            "STNEAR",
            "Staked NEAR",
            "crypto",
            "/assets/stnear",
            &["stnear", "staked near"],
            130,
        ),
        format_sample_asset(
            "usdt",
            "USDT",
            "Tether USD",
            "stablecoin",
            "/assets/usdt",
            &["usdt", "tether", "tether usd"],
            140,
        ),
        format_sample_asset(
            "usdt0",
            "USDT0",
            "USDT0",
            "stablecoin",
            "/assets/usdt0",
            &["usdt0", "usdt zero"],
            150,
        ),
        format_sample_asset(
            "usde",
            "USDe",
            "USDe",
            "stablecoin",
            "/assets/usde",
            &["usde"],
            160,
        ),
        format_sample_asset(
            "wrapped-ether",
            "WETH",
            "Wrapped Ether",
            "crypto",
            "/assets/wrapped-ether",
            &["weth", "wrapped ether", "wrapped eth"],
            170,
        ),
        format_sample_asset(
            "cmeth",
            "cmETH",
            "cmETH",
            "crypto",
            "/assets/cmeth",
            &["cmeth", "cmeth token"],
            180,
        ),
        format_sample_asset(
            "meth",
            "mETH",
            "mETH",
            "crypto",
            "/assets/meth",
            &["meth", "meth token"],
            190,
        ),
        format_sample_asset(
            "susde",
            "sUSDe",
            "sUSDe",
            "stablecoin",
            "/assets/susde",
            &["susde", "staked usde"],
            200,
        ),
    ]
}

pub(crate) fn format_sample_asset(
    slug: &str,
    symbol: &str,
    name: &str,
    category: &str,
    canonical_path: &str,
    aliases: &[&str],
    sort_order: i32,
) -> GlobalAsset {
    GlobalAsset {
        id: format!("test-{slug}"),
        slug: slug.to_string(),
        symbol: symbol.to_string(),
        name: name.to_string(),
        category: category.to_string(),
        canonical_path: canonical_path.to_string(),
        aliases: aliases.iter().map(|alias| alias.to_string()).collect(),
        sort_order,
    }
}
